name: makeapplist
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_list_maker: ^0.1.0
  args: ^2.2.0
  pub_api_client: 2.1.0
  yaml: ^3.1.0

dev_dependencies:
  mostly_reasonable_lints: ^0.1.1

dependency_overrides:
  mostly_reasonable_lints:
    path: ../../../mostly_reasonable_lints

executables:
  makeapplist: main
